approve_by_comment: true
approve_regex: '^(LGTM|:shipit:|:+1:)'
reject_regex: '^:-1:'
author_approval: ignored
reviewers:
    required: 1
    members:
        - ChristianMurphy
        - kgary
        - poojaRal
