rules:
    # String
    string-quotes: single
    # Color
    color-hex-case: lower
    color-hex-length: long
    color-no-hex: null
    color-no-invalid-hex: true
    color-no-named: null
    # Font Family
    font-family-name-quotes: single-where-recommended
    # Font Weight
    font-weight-notation: named
    # Number
    number-leading-zero: always
    number-max-precision: 2
    number-no-trailing-zeros: true
    number-zero-length-no-unit: true
    # Unit
    unit-whitelist:
        - px
        - "%"
    # Time
    time-no-imperceptible: true
    # Declaration
    declaration-bang-space-after: never
    declaration-bang-space-before: always
    declaration-colon-newline-after: null
    declaration-colon-space-after: always
    declaration-colon-space-before: never
    declaration-no-important: null
    # Declaration Block
    declaration-block-no-single-line: true
    declaration-block-semicolon-newline-after: always
    declaration-block-semicolon-newline-before: null
    declaration-block-semicolon-space-after: null
    declaration-block-semicolon-space-before: null
    declaration-block-single-line-max-declarations: null
    # Block
    block-closing-brace-newline-after: always
    block-closing-brace-newline-before: always
    block-closing-brace-space-after: null
    block-closing-brace-space-before: null
    block-no-empty: true
    block-opening-brace-newline-after: always
    block-opening-brace-newline-before: null
    block-opening-brace-space-after: null
    block-opening-brace-space-before: always
    # Selector
    selector-class-pattern: '^[a-z\-]+$'
    selector-combinator-space-after: always
    selector-combinator-space-before: always
    selector-id-pattern: null
    selector-no-attribute: null
    selector-no-combinator: null
    selector-no-id: null
    selector-no-type: true
    selector-no-universal: true
    selector-no-vendor-prefix: null
    selector-pseudo-element-colon-notation: double
    selector-root-no-composition: true
    # Selector List
    selector-list-comma-newline-after: always
    selector-list-comma-newline-before: null
    selector-list-comma-space-after: null
    selector-list-comma-space-before: null
    # Rule
    rule-nested-empty-line-before: null
    rule-no-duplicate-properties: true
    rule-no-shorthand-property-overrides: true
    rule-properties-order: null
    rule-trailing-semicolon: always
    # At Rule
    at-rule-empty-line-before: always
    at-rule-no-vendor-prefix: true
    # Comment
    comment-empty-line-before: null
    comment-whitespace-inside: always
    # General
    indentation: 4
    max-line-length: 120
    no-duplicate-selectors: true
    max-empty-lines: 1
    no-eol-whitespace: true
    no-invalid-double-slash-comments: true
    no-missing-eof-newline: true
    no-unknown-animations: true
